# Generated by Django 4.0 on 2023-11-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Описание')),
                ('lng_coordinates', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Долгота')),
                ('lat_coordinates', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Ширина')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='place_img', verbose_name='Фото места')),
                ('location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
        ),
    ]
