# Generated by Django 4.0 on 2023-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Описание')),
                ('lng_coordinates', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('lat_coordinates', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ширина')),
            ],
        ),
    ]
