# Generated by Django 4.0 on 2023-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat_coordinates',
            field=models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng_coordinates',
            field=models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Долгота'),
        ),
    ]
